release:
  github:
    owner: digitalsleuth
    repo: winfor-salt
manifest:
  version: 2
  name: winfor
  base_dir: winfor
  modes:
    - name: addon
      state: winfor.addon
    - name: dedicated
      state: winfor.dedicated
      default: true
  supported_os:
    - id: windows
      release: 10
    - id: windows
      release: 11
  saltstack:
    pillars:
      winfor_user_template: "{{ .User }}"
      inpath_template: '{{ default "C:\standalones" .inpath }}'
