# This workflow should download the latest Cygwin Installer,
# and compare the previous hash with the current hash. 

name: check-cygwin-hash

on:
  schedule:
      - cron: "0 0 * * *"
  
  workflow_dispatch:
 
jobs:
  cygwin_hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Check cygwin Hash
        run: |
          wget https://cygwin.com/setup-x86_64.exe
          PREVIOUS_HASH=$(cat /home/runner/work/winfor-salt/winfor-salt/winfor/installers/cygwin.sls | grep "set hash" | awk -F\' '{print tolower($2)}')
          CURRENT_HASH=$(sha256sum setup-x86_64.exe | awk '{print $1}')
          if [[ "$PREVIOUS_HASH" != "$CURRENT_HASH" ]]; then echo "HASH UPDATED - $CURRENT_HASH" && exit 1; else echo "No hash changes" && exit 0; fi
