# This workflow should query to see if the configured version of MSG Viewer is still available

name: check-msgviewer-exists

on:
  schedule:
      - cron: "0 0 * * *"
  
  workflow_dispatch:
 
jobs:
  msgviewer_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Check MSG Viewer presence
        run: |
          VER=$(cat /home/runner/work/winfor-salt/winfor-salt/winfor/downloads/packages/msg-viewer.sls | grep "set version" | awk -F\' '{print tolower($2)}')
          STATUS_CODE=$(curl -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0" -s -I https://downloads.pstwalker.com/msgviewer{$VER}.exe | grep "HTTP/2" | awk '{print $2}')
          if [[ "$STATUS_CODE" != "200" ]]; then echo "$STATUS_CODE - CURRENT VERSION OF MSG VIEWER $VER NOT AVAILABLE" && exit 1; else echo "MSG Viewer $VER still current version" && exit 0; fi

