# This workflow should download the latest PSDecode.psm1 module,
# and compare the previous hash with the current hash. 

name: check-psdecode-hash

on:
  schedule:
      - cron: "0 0 * * *"
  
  workflow_dispatch:
 
jobs:
  psdecode_hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Check PSDecode Hash
        run: |
          wget https://github.com/CybercentreCanada/assemblyline-service-overpower/raw/main/tools/PSDecode.psm1
          PREVIOUS_HASH=$(cat /home/runner/work/winfor-salt/winfor-salt/winfor/standalones/psdecode.sls | grep "set hash" | awk -F\' '{print $2}')
          CURRENT_HASH=$(sha256sum PSDecode.psm1 | awk '{print $1}')
          if [[ "$PREVIOUS_HASH" != "$CURRENT_HASH" ]]; then echo "HASH UPDATED - $CURRENT_HASH" && exit 1; else echo "No hash changes" && exit 0; fi

