# This workflow should download the latest SysinternalsSuite, and compare the previous hash 
# with the current hash. 

name: check-sysinternals-hash

on:
  schedule:
      - cron: "0 0 * * *"
  
  workflow_dispatch:
 
jobs:
  sysinternals_hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Check Sysinternals Hash
        run: |
          wget https://download.sysinternals.com/files/SysinternalsSuite.zip
          PREVIOUS_HASH=$(cat /home/runner/winfor/standalones/sysinternals.sls | grep "set hash" | awk -F\' '{print $2}')
          CURRENT_HASH=$(sha256sum SysinternalsSuite.zip | awk '{print $1}')
          [[ "$PREVIOUS_HASH" == "$CURRENT_HASH" ]]
          if [[ $? > 0 ]]; then echo $CURRENT_HASH; fi
